#!/bin/sh

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
MARKDOWN_PL=${MARKDOWN:-$SCRIPT_DIR/Markdown.pl}
MARKDOWN="perl $MARKDOWN_PL --html4tags"

head()
{
	file=$1
	title=$2

	cat <<EOF
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
	"http://www.w3.org/TR/html4/loose.dtd">
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="../shared/help.css" type="text/css" media="screen">
  <title>$title</title>
</head>
<body>
EOF
}

tail()
{
	cat <<EOF
</body>
</html>
EOF
}

while test -n "$1"; do
	file=$1
	title=$(sed -n '/^# /{s///;p;q;}' "$1")
	html="$(basename "${file%.*}.html")"
	echo "converting $file -> $html with title '$title'" >&2
	(head "$file" "$title"
	 $MARKDOWN "$file"
	 tail) > "$html"
	shift
done

